//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTinyRSS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyTinyRSS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Feeds.
        /// </summary>
        public static string AllFeedsSpecialFeed {
            get {
                return ResourceManager.GetString("AllFeedsSpecialFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Feeds.
        /// </summary>
        public static string AllFeedsTitle {
            get {
                return ResourceManager.GetString("AllFeedsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort: .
        /// </summary>
        public static string AppBarSortLabel {
            get {
                return ResourceManager.GetString("AppBarSortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny Tiny RSS Reader.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived Articles.
        /// </summary>
        public static string ArchivedFeeds {
            get {
                return ResourceManager.GetString("ArchivedFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelAppBarButtonText {
            get {
                return ResourceManager.GetString("CancelAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error activating live tile. Contact the developer, if this error happens more often..
        /// </summary>
        public static string ErrorAddLiveTile {
            get {
                return ResourceManager.GetString("ErrorAddLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string FailedConnection {
            get {
                return ResourceManager.GetString("FailedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Articles.
        /// </summary>
        public static string FreshFeeds {
            get {
                return ResourceManager.GetString("FreshFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...loading more Articles.
        /// </summary>
        public static string LoadMoreArticles {
            get {
                return ResourceManager.GetString("LoadMoreArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating feeds....
        /// </summary>
        public static string LoginProgress {
            get {
                return ResourceManager.GetString("LoginProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All as Read.
        /// </summary>
        public static string MarkAllArticlesRead {
            get {
                return ResourceManager.GetString("MarkAllArticlesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Read.
        /// </summary>
        public static string MarkReadAppBarButtonText {
            get {
                return ResourceManager.GetString("MarkReadAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Articles read automatically.
        /// </summary>
        public static string MarkReadSettings {
            get {
                return ResourceManager.GetString("MarkReadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Unread.
        /// </summary>
        public static string MarkUnreadAppBarButtonText {
            get {
                return ResourceManager.GetString("MarkUnreadAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Articles found here..
        /// </summary>
        public static string NoArticlesMessage {
            get {
                return ResourceManager.GetString("NoArticlesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection could be established. Check your settings..
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        public static string OpenExtAppBarButtonText {
            get {
                return ResourceManager.GetString("OpenExtAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordSettings {
            get {
                return ResourceManager.GetString("PasswordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Articles.
        /// </summary>
        public static string PublishedFeeds {
            get {
                return ResourceManager.GetString("PublishedFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Read.
        /// </summary>
        public static string RecentlyReadFeed {
            get {
                return ResourceManager.GetString("RecentlyReadFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshAppBarButtonText {
            get {
                return ResourceManager.GetString("RefreshAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string SaveAppBarButtonText {
            get {
                return ResourceManager.GetString("SaveAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings?.
        /// </summary>
        public static string SaveUnsavedSettings {
            get {
                return ResourceManager.GetString("SaveUnsavedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerSetting {
            get {
                return ResourceManager.GetString("ServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        public static string SettingsAboutAuthor {
            get {
                return ResourceManager.GetString("SettingsAboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Website.
        /// </summary>
        public static string SettingsAboutButtonProjectWeb {
            get {
                return ResourceManager.GetString("SettingsAboutButtonProjectWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose E-Mail.
        /// </summary>
        public static string SettingsAboutButtonSendLog {
            get {
                return ResourceManager.GetString("SettingsAboutButtonSendLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingsAboutHead {
            get {
                return ResourceManager.GetString("SettingsAboutHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-File of this session.
        /// </summary>
        public static string SettingsAboutRadioActualLog {
            get {
                return ResourceManager.GetString("SettingsAboutRadioActualLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-File of last session.
        /// </summary>
        public static string SettingsAboutRadioLastLog {
            get {
                return ResourceManager.GetString("SettingsAboutRadioLastLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach no logs.
        /// </summary>
        public static string SettingsAboutRadioNoLog {
            get {
                return ResourceManager.GetString("SettingsAboutRadioNoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following button to send me an E-Mail with your feedback. If you encountered an error it would be nice if you could attach a log file..
        /// </summary>
        public static string SettingsAboutText {
            get {
                return ResourceManager.GetString("SettingsAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string SettingsAboutVersion {
            get {
                return ResourceManager.GetString("SettingsAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Live Tile.
        /// </summary>
        public static string SettingsActivateLiveTile {
            get {
                return ResourceManager.GetString("SettingsActivateLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsAppBarButtonText {
            get {
                return ResourceManager.GetString("SettingsAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string SettingsConnectionHead {
            get {
                return ResourceManager.GetString("SettingsConnectionHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHead {
            get {
                return ResourceManager.GetString("SettingsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Tile.
        /// </summary>
        public static string SettingsLiveTile {
            get {
                return ResourceManager.GetString("SettingsLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you&apos;ve activated the live tile, the tile displays the count of new unread articles. This count can also be shown on your lockscreen. Simply choose the app from the lockscreen settings..
        /// </summary>
        public static string SettingsLiveTileInfo {
            get {
                return ResourceManager.GetString("SettingsLiveTileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lockscreen settings.
        /// </summary>
        public static string SettingsLiveTileLockScreenLink {
            get {
                return ResourceManager.GetString("SettingsLiveTileLockScreenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry there was an error creating the e-mail..
        /// </summary>
        public static string SettingsMailException {
            get {
                return ResourceManager.GetString("SettingsMailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Scrollbar instead of Counter on Articlepage.
        /// </summary>
        public static string SettingsScrollarAsCounter {
            get {
                return ResourceManager.GetString("SettingsScrollarAsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsSortDefault {
            get {
                return ResourceManager.GetString("SettingsSortDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string SettingsSortLabel {
            get {
                return ResourceManager.GetString("SettingsSortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest First.
        /// </summary>
        public static string SettingsSortNew {
            get {
                return ResourceManager.GetString("SettingsSortNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest First.
        /// </summary>
        public static string SettingsSortOld {
            get {
                return ResourceManager.GetString("SettingsSortOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval.
        /// </summary>
        public static string SettingsTileUpdatePeriod {
            get {
                return ResourceManager.GetString("SettingsTileUpdatePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Day.
        /// </summary>
        public static string SettingsUpdateDay {
            get {
                return ResourceManager.GetString("SettingsUpdateDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Half Hour.
        /// </summary>
        public static string SettingsUpdateHalfHour {
            get {
                return ResourceManager.GetString("SettingsUpdateHalfHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Hour.
        /// </summary>
        public static string SettingsUpdateHour {
            get {
                return ResourceManager.GetString("SettingsUpdateHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new credentials could not be sent to the live tile notfication server. Please try to uncheck/check the live tile checkbox or send me an e-mail..
        /// </summary>
        public static string SettingsUpdateLiveTileError {
            get {
                return ResourceManager.GetString("SettingsUpdateLiveTileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all Articles.
        /// </summary>
        public static string ShowAllArticles {
            get {
                return ResourceManager.GetString("ShowAllArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only unread Articles.
        /// </summary>
        public static string ShowOnlyUnreadArticles {
            get {
                return ResourceManager.GetString("ShowOnlyUnreadArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Feeds.
        /// </summary>
        public static string SpecialFeeds {
            get {
                return ResourceManager.GetString("SpecialFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Article.
        /// </summary>
        public static string StarAppBarButtonText {
            get {
                return ResourceManager.GetString("StarAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starred Articles.
        /// </summary>
        public static string StarredFeeds {
            get {
                return ResourceManager.GetString("StarredFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Successful.
        /// </summary>
        public static string SuccessfulConnection {
            get {
                return ResourceManager.GetString("SuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Server Login.
        /// </summary>
        public static string TestConnectionSettingsButton {
            get {
                return ResourceManager.GetString("TestConnectionSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Archived.
        /// </summary>
        public static string ToogleArchiveAppBarButtonText {
            get {
                return ResourceManager.GetString("ToogleArchiveAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Published.
        /// </summary>
        public static string TooglePublishAppBarButtonText {
            get {
                return ResourceManager.GetString("TooglePublishAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized.
        /// </summary>
        public static string Uncategorized {
            get {
                return ResourceManager.GetString("Uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an unexpected error occured. The app will close now..
        /// </summary>
        public static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only unread Articles from Feeds.
        /// </summary>
        public static string UnreadOnlySettings {
            get {
                return ResourceManager.GetString("UnreadOnlySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve made changes the haven&apos;t been saved..
        /// </summary>
        public static string UnsavedSettings {
            get {
                return ResourceManager.GetString("UnsavedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstar Article.
        /// </summary>
        public static string UnStarAppBarButtonText {
            get {
                return ResourceManager.GetString("UnStarAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserNameSettings {
            get {
                return ResourceManager.GetString("UserNameSettings", resourceCulture);
            }
        }
    }
}
