//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTinyRSS.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyTinyRSS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Feeds ähnelt.
        /// </summary>
        public static string AllFeedsSpecialFeed {
            get {
                return ResourceManager.GetString("AllFeedsSpecialFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Feeds ähnelt.
        /// </summary>
        public static string AllFeedsTitle {
            get {
                return ResourceManager.GetString("AllFeedsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort:  ähnelt.
        /// </summary>
        public static string AppBarSortLabel {
            get {
                return ResourceManager.GetString("AppBarSortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tiny Tiny RSS Reader ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archived Articles ähnelt.
        /// </summary>
        public static string ArchivedFeeds {
            get {
                return ResourceManager.GetString("ArchivedFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string CancelAppBarButtonText {
            get {
                return ResourceManager.GetString("CancelAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection Failed ähnelt.
        /// </summary>
        public static string FailedConnection {
            get {
                return ResourceManager.GetString("FailedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fresh Articles ähnelt.
        /// </summary>
        public static string FreshFeeds {
            get {
                return ResourceManager.GetString("FreshFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ...loading more Articles ähnelt.
        /// </summary>
        public static string LoadMoreArticles {
            get {
                return ResourceManager.GetString("LoadMoreArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating feeds... ähnelt.
        /// </summary>
        public static string LoginProgress {
            get {
                return ResourceManager.GetString("LoginProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark All as Read ähnelt.
        /// </summary>
        public static string MarkAllArticlesRead {
            get {
                return ResourceManager.GetString("MarkAllArticlesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark Read ähnelt.
        /// </summary>
        public static string MarkReadAppBarButtonText {
            get {
                return ResourceManager.GetString("MarkReadAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark Articles read automatically ähnelt.
        /// </summary>
        public static string MarkReadSettings {
            get {
                return ResourceManager.GetString("MarkReadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark Unread ähnelt.
        /// </summary>
        public static string MarkUnreadAppBarButtonText {
            get {
                return ResourceManager.GetString("MarkUnreadAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Articles found here. ähnelt.
        /// </summary>
        public static string NoArticlesMessage {
            get {
                return ResourceManager.GetString("NoArticlesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No connection could be established. Check your settings. ähnelt.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in Browser ähnelt.
        /// </summary>
        public static string OpenExtAppBarButtonText {
            get {
                return ResourceManager.GetString("OpenExtAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string PasswordSettings {
            get {
                return ResourceManager.GetString("PasswordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Published Articles ähnelt.
        /// </summary>
        public static string PublishedFeeds {
            get {
                return ResourceManager.GetString("PublishedFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recently Read ähnelt.
        /// </summary>
        public static string RecentlyReadFeed {
            get {
                return ResourceManager.GetString("RecentlyReadFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string RefreshAppBarButtonText {
            get {
                return ResourceManager.GetString("RefreshAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en-US ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string SaveAppBarButtonText {
            get {
                return ResourceManager.GetString("SaveAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server ähnelt.
        /// </summary>
        public static string ServerSetting {
            get {
                return ResourceManager.GetString("ServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author:  ähnelt.
        /// </summary>
        public static string SettingsAboutAuthor {
            get {
                return ResourceManager.GetString("SettingsAboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compose E-Mail ähnelt.
        /// </summary>
        public static string SettingsAboutButtonSendLog {
            get {
                return ResourceManager.GetString("SettingsAboutButtonSendLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string SettingsAboutHead {
            get {
                return ResourceManager.GetString("SettingsAboutHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log-File of this session ähnelt.
        /// </summary>
        public static string SettingsAboutRadioActualLog {
            get {
                return ResourceManager.GetString("SettingsAboutRadioActualLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log-File of last session ähnelt.
        /// </summary>
        public static string SettingsAboutRadioLastLog {
            get {
                return ResourceManager.GetString("SettingsAboutRadioLastLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attach no logs ähnelt.
        /// </summary>
        public static string SettingsAboutRadioNoLog {
            get {
                return ResourceManager.GetString("SettingsAboutRadioNoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use the following button to send me an E-Mail with your feedback. If you encountered an error it would be nice if you could attach a log file. ähnelt.
        /// </summary>
        public static string SettingsAboutText {
            get {
                return ResourceManager.GetString("SettingsAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version:  ähnelt.
        /// </summary>
        public static string SettingsAboutVersion {
            get {
                return ResourceManager.GetString("SettingsAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsAppBarButtonText {
            get {
                return ResourceManager.GetString("SettingsAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection ähnelt.
        /// </summary>
        public static string SettingsConnectionHead {
            get {
                return ResourceManager.GetString("SettingsConnectionHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsHead {
            get {
                return ResourceManager.GetString("SettingsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry there was an error creating the e-mail. ähnelt.
        /// </summary>
        public static string SettingsMailException {
            get {
                return ResourceManager.GetString("SettingsMailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Scrollbar instead of Counter on Articlepage ähnelt.
        /// </summary>
        public static string SettingsScrollarAsCounter {
            get {
                return ResourceManager.GetString("SettingsScrollarAsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string SettingsSortDefault {
            get {
                return ResourceManager.GetString("SettingsSortDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort Order ähnelt.
        /// </summary>
        public static string SettingsSortLabel {
            get {
                return ResourceManager.GetString("SettingsSortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Newest First ähnelt.
        /// </summary>
        public static string SettingsSortNew {
            get {
                return ResourceManager.GetString("SettingsSortNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oldest First ähnelt.
        /// </summary>
        public static string SettingsSortOld {
            get {
                return ResourceManager.GetString("SettingsSortOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show all Articles ähnelt.
        /// </summary>
        public static string ShowAllArticles {
            get {
                return ResourceManager.GetString("ShowAllArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show only unread Articles ähnelt.
        /// </summary>
        public static string ShowOnlyUnreadArticles {
            get {
                return ResourceManager.GetString("ShowOnlyUnreadArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special Feeds ähnelt.
        /// </summary>
        public static string SpecialFeeds {
            get {
                return ResourceManager.GetString("SpecialFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Star Article ähnelt.
        /// </summary>
        public static string StarAppBarButtonText {
            get {
                return ResourceManager.GetString("StarAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starred Articles ähnelt.
        /// </summary>
        public static string StarredFeeds {
            get {
                return ResourceManager.GetString("StarredFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection Successful ähnelt.
        /// </summary>
        public static string SuccessfulConnection {
            get {
                return ResourceManager.GetString("SuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Connection ähnelt.
        /// </summary>
        public static string TestConnectionSettingsButton {
            get {
                return ResourceManager.GetString("TestConnectionSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Archived ähnelt.
        /// </summary>
        public static string ToogleArchiveAppBarButtonText {
            get {
                return ResourceManager.GetString("ToogleArchiveAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Published ähnelt.
        /// </summary>
        public static string TooglePublishAppBarButtonText {
            get {
                return ResourceManager.GetString("TooglePublishAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uncategorized ähnelt.
        /// </summary>
        public static string Uncategorized {
            get {
                return ResourceManager.GetString("Uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, an unexpected error occured. The app will close now. ähnelt.
        /// </summary>
        public static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show only unread Articles from Feeds ähnelt.
        /// </summary>
        public static string UnreadOnlySettings {
            get {
                return ResourceManager.GetString("UnreadOnlySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unstar Article ähnelt.
        /// </summary>
        public static string UnStarAppBarButtonText {
            get {
                return ResourceManager.GetString("UnStarAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string UserNameSettings {
            get {
                return ResourceManager.GetString("UserNameSettings", resourceCulture);
            }
        }
    }
}
